# Generated by Django 5.1.1 on 2024-10-28 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='name',
        ),
    ]
