# Generated by Django 5.1.1 on 2024-10-28 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_good_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(upload_to='media', verbose_name='Фото'),
        ),
    ]
